# Generated by Django 5.2.3 on 2025-06-20 09:05

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[blog.validators.HTMLValidator()], verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[blog.validators.HTMLValidator()], verbose_name='Содержание'),
        ),
    ]
